EasyTravel/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyTravel.Database;
using System.IO;
using EasyTravel.Models;

namespace EasyTravel.Controllers
{
    [Authorize]
    public class DriversController : Controller
    {
        private EasyTravelEntities db = new EasyTravelEntities();

        // GET: Drivers
        public ActionResult Index()
        {
            var drivers = db.Drivers.Include(d => d.AspNetUser);
            return View(drivers.ToList());
        }

        // GET: Drivers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // GET: Drivers/Create
        public ActionResult Create()
        {
            IEnumerable<AspNetUser> drivers = db.AspNetUsers.Where(x => x.AspNetRoles.Contains(db.AspNetRoles.FirstOrDefault(y => y.Name == "Driver")));
            ViewBag.UserId = new SelectList(drivers, "Id", "Email");
            return View();
        }

        // POST: Drivers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,DrivingLicenseNumber,VehicleLicensePlate,Vehicle,VehicleModel,CnicNumber,AreDocumentsVerified,IsActive,PhotoFileName")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                try {
                    db.Drivers.Add(driver);
                    db.SaveChanges();
                }
                catch (Exception ex) {
                    throw ex;
                }
                if (!string.IsNullOrEmpty(driver.PhotoFileName)) {

                    string path = Server.MapPath("~/Uploads/Images/DriverPhotos/");
                    string fromFile = path + driver.PhotoFileName;
                    string toFile = String.Format("{0}{1}.png", path, driver.DrivingLicenseNumber);

                    if (System.IO.File.Exists(fromFile))
                        System.IO.File.Move(fromFile, toFile);
                }

                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", driver.UserId);
            return View(driver);
        }

        // GET: Drivers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            IEnumerable<AspNetUser> drivers = db.AspNetUsers.Where(x => x.AspNetRoles.Contains(db.AspNetRoles.FirstOrDefault(y => y.Name == "Driver")));
            ViewBag.UserId = new SelectList(drivers, "Id", "Email", driver.UserId);

            driver.PhotoFileName = driver.DrivingLicenseNumber + ".png";

            return View(driver);
        }

        // POST: Drivers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,DrivingLicenseNumber,VehicleLicensePlate,Vehicle,VehicleModel,CnicNumber,AreDocumentsVerified,IsActive,PhotoFileName")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Entry(driver).State = EntityState.Modified;
                db.SaveChanges();

                if (!string.IsNullOrEmpty(driver.PhotoFileName)) {

                    string path = Server.MapPath("~/Uploads/Images/DriverPhotos/");
                    string fromFile = path + driver.PhotoFileName;
                    string toFile = String.Format("{0}{1}.png", path, driver.DrivingLicenseNumber);

                    if (System.IO.File.Exists(fromFile))
                        System.IO.File.Move(fromFile, toFile);
                }

                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", driver.UserId);
            return View(driver);
        }

        // GET: Drivers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Driver driver = db.Drivers.Find(id);
            db.Drivers.Remove(driver);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult UploadPhoto (HttpPostedFileBase file)
        {
            string fileName = Guid.NewGuid().ToString() + ".png";

            try {
                if (file != null && file.ContentLength > 0) {

                    string name = file.FileName.Split('\\').Last();

                    var path = Path.Combine(this.Server.MapPath("~/Uploads/Images/DriverPhotos"), fileName);
                    file.SaveAs(path);

                    return Json(new { IsSuccess = true, fileName = fileName }, JsonRequestBehavior.AllowGet);

                }
                else {
                    return Json(new { IsSuccess = false, Message = "Please select some file" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception lex) {
                return Json(new { lex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

EasyTravel/Views/Drivers/Create.cshtml
@model EasyTravel.Database.Driver

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Driver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "User Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
               @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DrivingLicenseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DrivingLicenseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DrivingLicenseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleLicensePlate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleLicensePlate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleLicensePlate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vehicle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vehicle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vehicle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CnicNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CnicNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CnicNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => Model.Id, "Picture", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @{
                    string photoSrc = "~/Uploads/Images/DriverPhotos/placeholder.jpg";

                    //if (Model.Id != 0) {
                    //    photoSrc = "~/Uploads/Images/DriverPhotos/" + Model.Id + ".png";
                    //}
                }
                <img id="logo-image" style="height:100px; max-width: 100px;" src="@Url.Content(photoSrc)" onerror="this.src='@Url.Content("~/Uploads/Images/DriverPhotos/placeholder.jpg")'" class="img-responsive pull-left" alt="User Image">
                <br />
                <input type="file" class="form-control" onchange="UploadPhoto(this, '@Url.Action("UploadPhoto", "Drivers")');">
                <small>165px × 165px</small>
                @Html.HiddenFor(model => Model.PhotoFileName, new { @id = "PhotoFileId" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreDocumentsVerified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AreDocumentsVerified)
                    @Html.ValidationMessageFor(model => model.AreDocumentsVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    var photosPath = "@Url.Content("~/Uploads/Images/DriverPhotos/")";
</script>

@Scripts.Render("~/Scripts/EasyTravel.js")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyTravel/Views/Drivers/Delete.cshtml
@model EasyTravel.Database.Driver

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Driver</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DrivingLicenseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DrivingLicenseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleLicensePlate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleLicensePlate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CnicNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CnicNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AreDocumentsVerified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AreDocumentsVerified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EasyTravel/Views/Drivers/Details.cshtml
@model EasyTravel.Database.Driver

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Driver</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DrivingLicenseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DrivingLicenseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleLicensePlate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleLicensePlate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vehicle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vehicle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CnicNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CnicNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AreDocumentsVerified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AreDocumentsVerified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EasyTravel/Views/Drivers/Edit.cshtml
@model EasyTravel.Database.Driver

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Driver</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DrivingLicenseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DrivingLicenseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DrivingLicenseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleLicensePlate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleLicensePlate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleLicensePlate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vehicle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vehicle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vehicle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CnicNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CnicNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CnicNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => Model.Id, "Picture", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @{
                    string photoSrc = "~/Uploads/Images/DriverPhotos/placeholder.jpg";

                    if (!String.IsNullOrEmpty(Model.PhotoFileName)) {
                        photoSrc = "~/Uploads/Images/DriverPhotos/" + Model.PhotoFileName;
                    }
                }
                <img id="logo-image" style="height:100px; max-width: 100px;" src="@Url.Content(photoSrc)" onerror="this.src='@Url.Content("~/Uploads/Images/DriverPhotos/placeholder.jpg")'" class="img-responsive pull-left" alt="User Image">
                <br />
                <input type="file" class="form-control" onchange="UploadPhoto(this, '@Url.Action("UploadPhoto", "Drivers")');">
                <small>165px × 165px</small>
                @Html.HiddenFor(model => Model.PhotoFileName, new { @id = "PhotoFileId" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreDocumentsVerified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AreDocumentsVerified)
                    @Html.ValidationMessageFor(model => model.AreDocumentsVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    var photosPath = "@Url.Content("~/Uploads/Images/DriverPhotos/")";
</script>

@Scripts.Render("~/Scripts/EasyTravel.js")

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyTravel/Views/Drivers/Index.cshtml
@model IEnumerable<EasyTravel.Database.Driver>

@{
    ViewBag.Title = "Drivers";
}

<h2>Drivers</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-lg" })
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CnicNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DrivingLicenseNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleLicensePlate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vehicle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleModel)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.AreDocumentsVerified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.FirstName) @Html.DisplayFor(modelItem => item.AspNetUser.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CnicNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DrivingLicenseNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleLicensePlate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vehicle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleModel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AreDocumentsVerified)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>